# see: https://github.com/probot/settings

repository:
  name: action.build-and-push-image
  description: Github action to build, tag and push a Docker image
  topics: action
  private: false
  has_issues: false
  has_wiki: false
  is_template: false
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  archived: false

teams:
  - name: engineers
    permission: admin
  - name: engineers-pullassigner
    permission: push

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
